# Generated by Django 2.1.3 on 2018-11-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linia',
            fields=[
                ('id_linii', models.IntegerField(db_column='ID_Linii', primary_key=True, serialize=False)),
                ('numer_linii', models.IntegerField(db_column='Numer_Linii')),
            ],
            options={
                'db_table': 'linia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motorniczy',
            fields=[
                ('id_motorniczego', models.IntegerField(db_column='ID_Motorniczego', primary_key=True, serialize=False)),
                ('imie', models.CharField(db_column='Imie', max_length=45)),
                ('nazwisko', models.CharField(db_column='Nazwisko', max_length=45)),
                ('stawka', models.FloatField(db_column='Stawka')),
            ],
            options={
                'db_table': 'motorniczy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Praca',
            fields=[
                ('id_pracy', models.IntegerField(db_column='ID_Pracy', primary_key=True, serialize=False)),
                ('poczatekpracy', models.DateTimeField(db_column='PoczatekPracy')),
                ('koniecpracy', models.DateTimeField(blank=True, db_column='KoniecPracy', null=True)),
                ('czaspracy', models.FloatField(blank=True, db_column='CzasPracy', null=True)),
                ('wynagrodzenie', models.FloatField(db_column='Wynagrodzenie')),
            ],
            options={
                'db_table': 'praca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tramwaj',
            fields=[
                ('id_tramwaju', models.IntegerField(db_column='ID_Tramwaju', primary_key=True, serialize=False)),
                ('prog_godzinowy', models.IntegerField(db_column='Prog_Godzinowy')),
                ('aktualny_przebieg', models.FloatField(db_column='Aktualny_Przebieg')),
            ],
            options={
                'db_table': 'tramwaj',
                'managed': False,
            },
        ),
    ]
